M1_EVENT = 1
M3_EVENT = 2
MODEL_FILE_NAME_PREFIX = "model"
NOT_NAN_SUFFIX = "_not_NaN"
EXH_PREFIX = "E"
EXH_SEPARATOR = "_"
E_LIST_ID = [EXH_PREFIX + str(num) for num in range(0, 10)]
E_DICT = {"Эксгаустер " + str(num): E_LIST_ID[num] for num in range(4, 10)}
EXH_NAME_BY_ID = {E_DICT[exh_name]: exh_name for exh_name in E_DICT.keys()}

SENSOR_LIST = {
    "ЭКСГАУСТЕР 4. ТОК РОТОРА 1": {"BDName": E_LIST_ID[4] + EXH_SEPARATOR + "iRot1", "DispName": "Э4.iР1"},
    "ЭКСГАУСТЕР 4. ТОК РОТОРА2": {"BDName": E_LIST_ID[4] + EXH_SEPARATOR + "iRot2", "DispName": "Э4.iР2"},
    "ЭКСГАУСТЕР 4. ТОК СТАТОРА": {"BDName": E_LIST_ID[4] + EXH_SEPARATOR + "iSt", "DispName": "Э4.iС"},
    "ЭКСГАУСТЕР 4. ДАВЛЕНИЕ МАСЛА В СИСТЕМЕ": {"BDName": E_LIST_ID[4] + EXH_SEPARATOR + "pМSt", "DispName": "Э4.pМС"},
    "ЭКСГАУСТЕР 4. ТЕМПЕРАТУРА ПОДШИПНИКА НА ОПОРЕ 1": {"BDName": E_LIST_ID[4] + EXH_SEPARATOR + "tBrSup1", "DispName": "Э4.tПО1"},
    "ЭКСГАУСТЕР 4. ТЕМПЕРАТУРА ПОДШИПНИКА НА ОПОРЕ 2": {"BDName": E_LIST_ID[4] + EXH_SEPARATOR + "tBrSup2", "DispName": "Э4.tПО2"},
    "ЭКСГАУСТЕР 4. ТЕМПЕРАТУРА ПОДШИПНИКА НА ОПОРЕ 3": {"BDName": E_LIST_ID[4] + EXH_SEPARATOR + "tBrSup3", "DispName": "Э4.tПО3"},
    "ЭКСГАУСТЕР 4. ТЕМПЕРАТУРА ПОДШИПНИКА НА ОПОРЕ 4": {"BDName": E_LIST_ID[4] + EXH_SEPARATOR + "tBrSup4", "DispName": "Э4.tПО4"},
    "ЭКСГАУСТЕР 4. ТЕМПЕРАТУРА МАСЛА В СИСТЕМЕ": {"BDName": E_LIST_ID[4] + EXH_SEPARATOR + "tМSt", "DispName": "Э4.tМС"},
    "ЭКСГАУСТЕР 4. ТЕМПЕРАТУРА МАСЛА В МАСЛОБЛОКЕ": {"BDName": E_LIST_ID[4] + EXH_SEPARATOR + "tММ", "DispName": "Э4.tММ"},
    "ЭКСГАУСТЕР 4. ВИБРАЦИЯ НА ОПОРЕ 1": {"BDName": E_LIST_ID[4] + EXH_SEPARATOR + "vSup1", "DispName": "Э4.vО1"},
    "ЭКСГАУСТЕР 4. ВИБРАЦИЯ НА ОПОРЕ 2": {"BDName": E_LIST_ID[4] + EXH_SEPARATOR + "vSup2", "DispName": "Э4.vО2"},
    "ЭКСГАУСТЕР 4. ВИБРАЦИЯ НА ОПОРЕ 3": {"BDName": E_LIST_ID[4] + EXH_SEPARATOR + "vSup3", "DispName": "Э4.vО3"},
    "ЭКСГАУСТЕР 4. ВИБРАЦИЯ НА ОПОРЕ 3. ПРОДОЛЬНАЯ.": {"BDName": E_LIST_ID[4] + EXH_SEPARATOR + "vSup3L", "DispName": "Э4.vО3п"},
    "ЭКСГАУСТЕР 4. ВИБРАЦИЯ НА ОПОРЕ 4": {"BDName": E_LIST_ID[4] + EXH_SEPARATOR + "vSup4", "DispName": "Э4.vО4"},
    "ЭКСГАУСТЕР 4. ВИБРАЦИЯ НА ОПОРЕ 4. ПРОДОЛЬНАЯ.": {"BDName": E_LIST_ID[4] + EXH_SEPARATOR + "vSup4L", "DispName": "Э4.vО4п"},
    "ЭКСГАУСТЕР 5. ТОК РОТОРА 1": {"BDName": E_LIST_ID[5] + EXH_SEPARATOR + "iRot1", "DispName": "Э5.iР1"},
    "ЭКСГАУСТЕР 5. ТОК РОТОРА 2": {"BDName": E_LIST_ID[5] + EXH_SEPARATOR + "iRot2", "DispName": "Э5.iР2"},
    "ЭКСГАУСТЕР 5. ТОК СТАТОРА": {"BDName": E_LIST_ID[5] + EXH_SEPARATOR + "iSt", "DispName": "Э5.iС"},
    "ЭКСГАУСТЕР 5. ДАВЛЕНИЕ МАСЛА В СИСТЕМЕ": {"BDName": E_LIST_ID[5] + EXH_SEPARATOR + "p", "DispName": "Э5.p"},
    "ЭКСГАУСТЕР 5. ТЕМПЕРАТУРА ПОДШИПНИКА НА ОПОРЕ 1": {"BDName": E_LIST_ID[5] + EXH_SEPARATOR + "tBrSup1", "DispName": "Э5.tПО1"},
    "ЭКСГАУСТЕР 5. ТЕМПЕРАТУРА ПОДШИПНИКА НА ОПОРЕ 2": {"BDName": E_LIST_ID[5] + EXH_SEPARATOR + "tBrSup2", "DispName": "Э5.tПО2"},
    "ЭКСГАУСТЕР 5. ТЕМПЕРАТУРА ПОДШИПНИКА НА ОПОРЕ 3": {"BDName": E_LIST_ID[5] + EXH_SEPARATOR + "tBrSup3", "DispName": "Э5.tПО3"},
    "ЭКСГАУСТЕР 5. ТЕМПЕРАТУРА ПОДШИПНИКА НА ОПОРЕ 4": {"BDName": E_LIST_ID[5] + EXH_SEPARATOR + "tBrSup4", "DispName": "Э5.tПО4"},
    "ЭКСГАУСТЕР 5. ТЕМПЕРАТУРА МАСЛА В СИСТЕМЕ": {"BDName": E_LIST_ID[5] + EXH_SEPARATOR + "tМSt", "DispName": "Э5.tМС"},
    "ЭКСГАУСТЕР 5. ТЕМПЕРАТУРА МАСЛА В МАСЛОБЛОКЕ": {"BDName": E_LIST_ID[5] + EXH_SEPARATOR + "tММ", "DispName": "Э5.tММ"},
    "ЭКСГАУСТЕР 5. ВИБРАЦИЯ НА ОПОРЕ 1": {"BDName": E_LIST_ID[5] + EXH_SEPARATOR + "vSup1", "DispName": "Э5.vО1"},
    "ЭКСГАУСТЕР 5. ВИБРАЦИЯ НА ОПОРЕ 2": {"BDName": E_LIST_ID[5] + EXH_SEPARATOR + "vSup2", "DispName": "Э5.vО2"},
    "ЭКСГАУСТЕР 5. ВИБРАЦИЯ НА ОПОРЕ 3": {"BDName": E_LIST_ID[5] + EXH_SEPARATOR + "vSup3", "DispName": "Э5.vО3"},
    "ЭКСГАУСТЕР 5. ВИБРАЦИЯ НА ОПОРЕ 3. ПРОДОЛЬНАЯ.": {"BDName": E_LIST_ID[5] + EXH_SEPARATOR + "vSup3L", "DispName": "Э5.vО3п"},
    "ЭКСГАУСТЕР 5. ВИБРАЦИЯ НА ОПОРЕ 4": {"BDName": E_LIST_ID[5] + EXH_SEPARATOR + "vSup4", "DispName": "Э5.vО4"},
    "ЭКСГАУСТЕР 5. ВИБРАЦИЯ НА ОПОРЕ 4. ПРОДОЛЬНАЯ.": {"BDName": E_LIST_ID[5] + EXH_SEPARATOR + "vSup4L", "DispName": "Э5.vО4п"},
    "ЭКСГАУСТЕР 6. ТОК РОТОРА 1": {"BDName": E_LIST_ID[6] + EXH_SEPARATOR + "iRot1", "DispName": "Э6.iР1"},
    "ЭКСГАУСТЕР 6. ТОК РОТОРА 2": {"BDName": E_LIST_ID[6] + EXH_SEPARATOR + "iRot2", "DispName": "Э6.iР2"},
    "ЭКСГАУСТЕР 6. ТОК СТАТОРА": {"BDName": E_LIST_ID[6] + EXH_SEPARATOR + "iSt", "DispName": "Э6.iС"},
    "ЭКСГАУСТЕР 6. ДАВЛЕНИЕ МАСЛА В СИСТЕМЕ": {"BDName": E_LIST_ID[6] + EXH_SEPARATOR + "pМSt", "DispName": "Э6.pМС"},
    "ЭКСГАУСТЕР 6. ТЕМПЕРАТУРА ПОДШИПНИКА НА ОПОРЕ 1": {"BDName": E_LIST_ID[6] + EXH_SEPARATOR + "tBrSup1", "DispName": "Э6.tПО1"},
    "ЭКСГАУСТЕР 6. ТЕМПЕРАТУРА ПОДШИПНИКА НА ОПОРЕ 2": {"BDName": E_LIST_ID[6] + EXH_SEPARATOR + "tBrSup2", "DispName": "Э6.tПО2"},
    "ЭКСГАУСТЕР 6. ТЕМПЕРАТУРА ПОДШИПНИКА НА ОПОРЕ 3": {"BDName": E_LIST_ID[6] + EXH_SEPARATOR + "tBrSup3", "DispName": "Э6.tПО3"},
    "ЭКСГАУСТЕР 6. ТЕМПЕРАТУРА ПОДШИПНИКА НА ОПОРЕ 4": {"BDName": E_LIST_ID[6] + EXH_SEPARATOR + "tBrSup4", "DispName": "Э6.tПО4"},
    "ЭКСГАУСТЕР 6. ТЕМПЕРАТУРА МАСЛА В СИСТЕМЕ": {"BDName": E_LIST_ID[6] + EXH_SEPARATOR + "tМSt", "DispName": "Э6.tМС"},
    "ЭКСГАУСТЕР 6. ТЕМПЕРАТУРА МАСЛА В МАСЛОБЛОКЕ": {"BDName": E_LIST_ID[6] + EXH_SEPARATOR + "tММ", "DispName": "Э6.tММ"},
    "ЭКСГАУСТЕР 6. ВИБРАЦИЯ НА ОПОРЕ 1": {"BDName": E_LIST_ID[6] + EXH_SEPARATOR + "vSup1", "DispName": "Э6.vО1"},
    "ЭКСГАУСТЕР 6. ВИБРАЦИЯ НА ОПОРЕ 2": {"BDName": E_LIST_ID[6] + EXH_SEPARATOR + "vSup2", "DispName": "Э6.vО2"},
    "ЭКСГАУСТЕР 6. ВИБРАЦИЯ НА ОПОРЕ 3": {"BDName": E_LIST_ID[6] + EXH_SEPARATOR + "vSup3", "DispName": "Э6.vО3"},
    "ЭКСГАУСТЕР 6. ВИБРАЦИЯ НА ОПОРЕ 3. ПРОДОЛЬНАЯ.": {"BDName": E_LIST_ID[6] + EXH_SEPARATOR + "vSup3L", "DispName": "Э6.vО3п"},
    "ЭКСГАУСТЕР 6. ВИБРАЦИЯ НА ОПОРЕ 4": {"BDName": E_LIST_ID[6] + EXH_SEPARATOR + "vSup4", "DispName": "Э6.vО4"},
    "ЭКСГАУСТЕР 6. ВИБРАЦИЯ НА ОПОРЕ 4. ПРОДОЛЬНАЯ.": {"BDName": E_LIST_ID[6] + EXH_SEPARATOR + "vSup4L", "DispName": "Э6.vО4п"},
    "ЭКСГАУСТЕР 7. ТОК РОТОРА 1": {"BDName": E_LIST_ID[7] + EXH_SEPARATOR + "iRot1", "DispName": "Э7.iР1"},
    "ЭКСГАУСТЕР 7. ТОК РОТОРА 2": {"BDName": E_LIST_ID[7] + EXH_SEPARATOR + "iRot2", "DispName": "Э7.iР2"},
    "ЭКСГАУСТЕР 7. ТОК СТАТОРА": {"BDName": E_LIST_ID[7] + EXH_SEPARATOR + "iSt", "DispName": "Э7.iС"},
    "ЭКСГАУСТЕР 7. ДАВЛЕНИЕ МАСЛА В СИСТЕМЕ": {"BDName": E_LIST_ID[7] + EXH_SEPARATOR + "pМSt", "DispName": "Э7.pМС"},
    "ЭКСГАУСТЕР 7. ТЕМПЕРАТУРА ПОДШИПНИКА НА ОПОРЕ 1": {"BDName": E_LIST_ID[7] + EXH_SEPARATOR + "tBrSup1", "DispName": "Э7.tПО1"},
    "ЭКСГАУСТЕР 7. ТЕМПЕРАТУРА ПОДШИПНИКА НА ОПОРЕ 2": {"BDName": E_LIST_ID[7] + EXH_SEPARATOR + "tBrSup2", "DispName": "Э7.tПО2"},
    "ЭКСГАУСТЕР 7. ТЕМПЕРАТУРА ПОДШИПНИКА НА ОПОРЕ 3": {"BDName": E_LIST_ID[7] + EXH_SEPARATOR + "tBrSup3", "DispName": "Э7.tПО3"},
    "ЭКСГАУСТЕР 7. ТЕМПЕРАТУРА ПОДШИПНИКА НА ОПОРЕ 4": {"BDName": E_LIST_ID[7] + EXH_SEPARATOR + "tBrSup4", "DispName": "Э7.tПО4"},
    "ЭКСГАУСТЕР 7. ТЕМПЕРАТУРА МАСЛА В СИСТЕМЕ": {"BDName": E_LIST_ID[7] + EXH_SEPARATOR + "tМSt", "DispName": "Э7.tМС"},
    "ЭКСГАУСТЕР 7. ТЕМПЕРАТУРА МАСЛА В МАСЛОБЛОКЕ": {"BDName": E_LIST_ID[7] + EXH_SEPARATOR + "tММ", "DispName": "Э7.tММ"},
    "ЭКСГАУСТЕР 7. ВИБРАЦИЯ НА ОПОРЕ 1": {"BDName": E_LIST_ID[7] + EXH_SEPARATOR + "vSup1", "DispName": "Э7.vО1"},
    "ЭКСГАУСТЕР 7. ВИБРАЦИЯ НА ОПОРЕ 2": {"BDName": E_LIST_ID[7] + EXH_SEPARATOR + "vSup2", "DispName": "Э7.vО2"},
    "ЭКСГАУСТЕР 7. ВИБРАЦИЯ НА ОПОРЕ 3": {"BDName": E_LIST_ID[7] + EXH_SEPARATOR + "vSup3", "DispName": "Э7.vО3"},
    "ЭКСГАУСТЕР 7. ВИБРАЦИЯ НА ОПОРЕ 3. ПРОДОЛЬНАЯ.": {"BDName": E_LIST_ID[7] + EXH_SEPARATOR + "vSup3L", "DispName": "Э7.vО3п"},
    "ЭКСГАУСТЕР 7. ВИБРАЦИЯ НА ОПОРЕ 4": {"BDName": E_LIST_ID[7] + EXH_SEPARATOR + "vSup4", "DispName": "Э7.vО4"},
    "ЭКСГАУСТЕР 7. ВИБРАЦИЯ НА ОПОРЕ 4. ПРОДОЛЬНАЯ.": {"BDName": E_LIST_ID[7] + EXH_SEPARATOR + "v4L", "DispName": "Э7.v4п"},
    "ЭКСГАУСТЕР 8. ТОК РОТОРА 1": {"BDName": E_LIST_ID[8] + EXH_SEPARATOR + "iRot1", "DispName": "Э8.iР1"},
    "ЭКСГАУСТЕР 8. ТОК РОТОРА 2": {"BDName": E_LIST_ID[8] + EXH_SEPARATOR + "iRot2", "DispName": "Э8.iР2"},
    "ЭКСГАУСТЕР 8. ТОК СТАТОРА": {"BDName": E_LIST_ID[8] + EXH_SEPARATOR + "iSt", "DispName": "Э8.iС"},
    "ЭКСГАУСТЕР 8. ДАВЛЕНИЕ МАСЛА В СИСТЕМЕ": {"BDName": E_LIST_ID[8] + EXH_SEPARATOR + "pМSt", "DispName": "Э8.pМС"},
    "ЭКСГАУСТЕР 8. ТЕМПЕРАТУРА ПОДШИПНИКА НА ОПОРЕ 1": {"BDName": E_LIST_ID[8] + EXH_SEPARATOR + "tBrSup1", "DispName": "Э8.tПО1"},
    "ЭКСГАУСТЕР 8. ТЕМПЕРАТУРА ПОДШИПНИКА НА ОПОРЕ 2": {"BDName": E_LIST_ID[8] + EXH_SEPARATOR + "tBrSup2", "DispName": "Э8.tПО2"},
    "ЭКСГАУСТЕР 8. ТЕМПЕРАТУРА ПОДШИПНИКА НА ОПОРЕ 3": {"BDName": E_LIST_ID[8] + EXH_SEPARATOR + "tBrSup3", "DispName": "Э8.tПО3"},
    "ЭКСГАУСТЕР 8. ТЕМПЕРАТУРА ПОДШИПНИКА НА ОПОРЕ 4": {"BDName": E_LIST_ID[8] + EXH_SEPARATOR + "tBrSup4", "DispName": "Э8.tПО4"},
    "ЭКСГАУСТЕР 8. ТЕМПЕРАТУРА МАСЛА В СИСТЕМЕ": {"BDName": E_LIST_ID[8] + EXH_SEPARATOR + "tМSt", "DispName": "Э8.tМС"},
    "ЭКСГАУСТЕР 8. ТЕМПЕРАТУРА МАСЛА В МАСЛОБЛОКЕ": {"BDName": E_LIST_ID[8] + EXH_SEPARATOR + "tММ", "DispName": "Э8.tММ"},
    "ЭКСГАУСТЕР 8. ВИБРАЦИЯ НА ОПОРЕ 1": {"BDName": E_LIST_ID[8] + EXH_SEPARATOR + "vSup1", "DispName": "Э8.vО1"},
    "ЭКСГАУСТЕР 8. ВИБРАЦИЯ НА ОПОРЕ 2": {"BDName": E_LIST_ID[8] + EXH_SEPARATOR + "vSup2", "DispName": "Э8.vО2"},
    "ЭКСГАУСТЕР 8. ВИБРАЦИЯ НА ОПОРЕ 3": {"BDName": E_LIST_ID[8] + EXH_SEPARATOR + "vSup3", "DispName": "Э8.vО3"},
    "ЭКСГАУСТЕР 8. ВИБРАЦИЯ НА ОПОРЕ 3. ПРОДОЛЬНАЯ.": {"BDName": E_LIST_ID[8] + EXH_SEPARATOR + "vSup3L", "DispName": "Э8.vО3п"},
    "ЭКСГАУСТЕР 8. ВИБРАЦИЯ НА ОПОРЕ 4": {"BDName": E_LIST_ID[8] + EXH_SEPARATOR + "vSup4", "DispName": "Э8.vО4"},
    "ЭКСГАУСТЕР 8. ВИБРАЦИЯ НА ОПОРЕ 4. ПРОДОЛЬНАЯ.": {"BDName": E_LIST_ID[8] + EXH_SEPARATOR + "vSup4L", "DispName": "Э8.vО4п"},
    "ЭКСГАУСТЕР 9. ТОК РОТОРА 1": {"BDName": E_LIST_ID[9] + EXH_SEPARATOR + "iRot1", "DispName": "Э9.iР1"},
    "ЭКСГАУСТЕР 9. ТОК РОТОРА 2": {"BDName": E_LIST_ID[9] + EXH_SEPARATOR + "iRot2", "DispName": "Э9.iР2"},
    "ЭКСГАУСТЕР 9. ТОК СТАТОРА": {"BDName": E_LIST_ID[9] + EXH_SEPARATOR + "iSt", "DispName": "Э9.iС"},
    "ЭКСГАУСТЕР 9. ДАВЛЕНИЕ МАСЛА В СИСТЕМЕ": {"BDName": E_LIST_ID[9] + EXH_SEPARATOR + "pМSt", "DispName": "Э9.pМС"},
    "ЭКСГАУСТЕР 9. ТЕМПЕРАТУРА ПОДШИПНИКА НА ОПОРЕ 1": {"BDName": E_LIST_ID[9] + EXH_SEPARATOR + "tSup1", "DispName": "Э9.tО1"},
    "ЭКСГАУСТЕР 9. ТЕМПЕРАТУРА ПОДШИПНИКА НА ОПОРЕ 2": {"BDName": E_LIST_ID[9] + EXH_SEPARATOR + "tSup2", "DispName": "Э9.tО2"},
    "ЭКСГАУСТЕР 9. ТЕМПЕРАТУРА ПОДШИПНИКА НА ОПОРЕ 3": {"BDName": E_LIST_ID[9] + EXH_SEPARATOR + "tSup3", "DispName": "Э9.tО3"},
    "ЭКСГАУСТЕР 9. ТЕМПЕРАТУРА ПОДШИПНИКА НА ОПОРЕ 4": {"BDName": E_LIST_ID[9] + EXH_SEPARATOR + "tSup4", "DispName": "Э9.tО4"},
    "ЭКСГАУСТЕР 9. ТЕМПЕРАТУРА МАСЛА В СИСТЕМЕ": {"BDName": E_LIST_ID[9] + EXH_SEPARATOR + "tМSt", "DispName": "Э9.tМС"},
    "ЭКСГАУСТЕР 9. ТЕМПЕРАТУРА МАСЛА В МАСЛОБЛОКЕ": {"BDName": E_LIST_ID[9] + EXH_SEPARATOR + "tММ", "DispName": "Э9.tММ"},
    "ЭКСГАУСТЕР 9. ВИБРАЦИЯ НА ОПОРЕ 1": {"BDName": E_LIST_ID[9] + EXH_SEPARATOR + "vSup1", "DispName": "Э9.vО1"},
    "ЭКСГАУСТЕР 9. ВИБРАЦИЯ НА ОПОРЕ 2": {"BDName": E_LIST_ID[9] + EXH_SEPARATOR + "vSup2", "DispName": "Э9.vО2"},
    "ЭКСГАУСТЕР 9. ВИБРАЦИЯ НА ОПОРЕ 3": {"BDName": E_LIST_ID[9] + EXH_SEPARATOR + "vSup3", "DispName": "Э9.vО3"},
    "ЭКСГАУСТЕР 9. ВИБРАЦИЯ НА ОПОРЕ 3. ПРОДОЛЬНАЯ.": {"BDName": E_LIST_ID[9] + EXH_SEPARATOR + "vSup3L", "DispName": "Э9.vО3п"},
    "ЭКСГАУСТЕР 9. ВИБРАЦИЯ НА ОПОРЕ 4": {"BDName": E_LIST_ID[9] + EXH_SEPARATOR + "vSup4", "DispName": "Э9.vО4"},
    "ЭКСГАУСТЕР 9. ВИБРАЦИЯ НА ОПОРЕ 4. ПРОДОЛЬНАЯ.": {"BDName": E_LIST_ID[9] + EXH_SEPARATOR + "vSup4L", "DispName": "Э9.vО4п"},
}

# Проверим чтобы каждое название столбца для таблицы было использовано только один раз
for element in SENSOR_LIST.keys():
    counter = 0
    for test_element in SENSOR_LIST.keys():
        if SENSOR_LIST[test_element]["BDName"] == SENSOR_LIST[element]["BDName"]:
            counter += 1

    if counter > 1:
        print(f"Название столбца [{SENSOR_LIST[element]['BDName']}] для датчика [{element}], дублируется.")

for element in SENSOR_LIST.keys():
    # Если не указано название для вывода на экран,
    # то используем короткое имя, предназначенное
    # для названия столбца в таблице
    if SENSOR_LIST[element]["DispName"] == "":
        SENSOR_LIST[element]["DispName"] = SENSOR_LIST[element]["BDName"]

# Создадим словарь, содержащий подстановку названий столбцов
SENSOR_FIELD_NAMES_LIST = {}
for element in SENSOR_LIST.keys():
    SENSOR_FIELD_NAMES_LIST[element] = SENSOR_LIST[element]["BDName"]

Y_LIST = {
    "Y_ЭКСГАУСТЕР А/М №4_ВК 310С ВИБРОПРЕОБРАЗОВАТЕЛЬ ЭКСГ.№4 Т.1": E_LIST_ID[4] + EXH_SEPARATOR + "N001",
    "Y_ЭКСГАУСТЕР А/М №4_ГСМ ЭКСГ. №4": E_LIST_ID[4] + EXH_SEPARATOR + "N002",
    "Y_ЭКСГАУСТЕР А/М №4_ЗАДВИЖКА ЭКСГ. №4": E_LIST_ID[4] + EXH_SEPARATOR + "N003",
    "Y_ЭКСГАУСТЕР А/М №4_ЗАП. И РЕГ. АРМАТУРА ЭКСГ.№4": E_LIST_ID[4] + EXH_SEPARATOR + "N004",
    "Y_ЭКСГАУСТЕР А/М №4_КЛ1 ТР№4 ДО ЭД ЭКСГАУСТЕРА №4": E_LIST_ID[4] + EXH_SEPARATOR + "N005",
    "Y_ЭКСГАУСТЕР А/М №4_КЛ2 ТР№4 ДО ЭД ЭКСГАУСТЕРА №4": E_LIST_ID[4] + EXH_SEPARATOR + "N006",
    "Y_ЭКСГАУСТЕР А/М №4_МАСЛОНАСОС РАБОЧИЙ ЭКСГ. №4": E_LIST_ID[4] + EXH_SEPARATOR + "N007",
    "Y_ЭКСГАУСТЕР А/М №4_МАСЛООХЛАДИТЕЛЬ  М-05-1 ЭКСГ. №4": E_LIST_ID[4] + EXH_SEPARATOR + "N008",
    "Y_ЭКСГАУСТЕР А/М №4_МАСЛОПРОВОДЫ ЭКСГ №4": E_LIST_ID[4] + EXH_SEPARATOR + "N009",
    "Y_ЭКСГАУСТЕР А/М №4_ПОДШИПНИК ОПОРНО-УПОРНЫЙ ЭКСГ. №4": E_LIST_ID[4] + EXH_SEPARATOR + "N010",
    "Y_ЭКСГАУСТЕР А/М №4_ПОДШИПНИК ОПОРНЫЙ №1 ЭКСГ. №4": E_LIST_ID[4] + EXH_SEPARATOR + "N011",
    "Y_ЭКСГАУСТЕР А/М №4_ПОДШИПНИК ОПОРНЫЙ №2 ЭКСГ. №4": E_LIST_ID[4] + EXH_SEPARATOR + "N012",
    "Y_ЭКСГАУСТЕР А/М №4_ПОДШИПНИК ОПОРНЫЙ ЭКСГ. №4": E_LIST_ID[4] + EXH_SEPARATOR + "N013",
    "Y_ЭКСГАУСТЕР А/М №4_РЕДУКТОР ГАЗ. ЗАДВИЖКИ ЭКСГ. №4": E_LIST_ID[4] + EXH_SEPARATOR + "N014",
    "Y_ЭКСГАУСТЕР А/М №4_РОТОР ЭКСГ. №4": E_LIST_ID[4] + EXH_SEPARATOR + "N015",
    "Y_ЭКСГАУСТЕР А/М №4_ТИРИСТ. ВОЗБУДИТЕЛЬ ВТ-РЭМ-400 ЭКСГ4 ВУ1": E_LIST_ID[4] + EXH_SEPARATOR + "N016",
    "Y_ЭКСГАУСТЕР А/М №4_ТР-Р ТМ-4000-10/6 ЭКСГ. №4": E_LIST_ID[4] + EXH_SEPARATOR + "N017",
    "Y_ЭКСГАУСТЕР А/М №4_ТСМТ-101-010-50М-400 ТЕРМОПР.ПОДШ.Т.1": E_LIST_ID[4] + EXH_SEPARATOR + "N018",
    "Y_ЭКСГАУСТЕР А/М №4_УЛИТА ЭКСГ. №4": E_LIST_ID[4] + EXH_SEPARATOR + "N019",
    "Y_ЭКСГАУСТЕР А/М №4_ЭКСГАУСТЕР А/М №4": E_LIST_ID[4] + EXH_SEPARATOR + "N020",
    "Y_ЭКСГАУСТЕР А/М №4_ЭЛ/ДВИГАТЕЛЬ ГАЗ. ЗАДВИЖКИ ЭКСГ. №4": E_LIST_ID[4] + EXH_SEPARATOR + "N021",
    "Y_ЭКСГАУСТЕР А/М №4_ЭЛЕКТРОАППАРАТУРА ЭКСГ. №4": E_LIST_ID[4] + EXH_SEPARATOR + "N022",
    "Y_ЭКСГАУСТЕР А/М №4_ЭЛЕКТРОДВИГАТЕЛЬ ДСПУ-140-84-4 ЭКСГ. №4": E_LIST_ID[4] + EXH_SEPARATOR + "N023",
    "Y_ЭКСГАУСТЕР А/М №5_ВК 310С ВИБРОПРЕОБРАЗОВАТЕЛЬ ЭКСГ.№5 Т.1": E_LIST_ID[5] + EXH_SEPARATOR + "N024",
    "Y_ЭКСГАУСТЕР А/М №5_ВК 310С ВИБРОПРЕОБРАЗОВАТЕЛЬ ЭКСГ.№5 Т.2": E_LIST_ID[5] + EXH_SEPARATOR + "N025",
    "Y_ЭКСГАУСТЕР А/М №5_ВК 310С ВИБРОПРЕОБРАЗОВАТЕЛЬ ЭКСГ.№5 Т.3": E_LIST_ID[5] + EXH_SEPARATOR + "N026",
    "Y_ЭКСГАУСТЕР А/М №5_ГАЗОВАЯ ЗАДВИЖКА ЭКСГАУСТЕРА А/М №5": E_LIST_ID[5] + EXH_SEPARATOR + "N027",
    "Y_ЭКСГАУСТЕР А/М №5_ГСМ ЭКСГ. №5": E_LIST_ID[5] + EXH_SEPARATOR + "N028",
    "Y_ЭКСГАУСТЕР А/М №5_ДВИГАТЕЛЬ ПУСКОВОГО МАСЛОНАСОСА ЭКСГ. №5": E_LIST_ID[5] + EXH_SEPARATOR + "N029",
    "Y_ЭКСГАУСТЕР А/М №5_ДВИГАТЕЛЬ РЕЗЕРВНОГО МАСЛОНАСОСА ЭКСГ.№5": E_LIST_ID[5] + EXH_SEPARATOR + "N030",
    "Y_ЭКСГАУСТЕР А/М №5_ЗАДВИЖКА ЭКСГ. №5": E_LIST_ID[5] + EXH_SEPARATOR + "N031",
    "Y_ЭКСГАУСТЕР А/М №5_ЗАПОРНАЯ АРМАТУРА ЭКСГАУСТЕРА №5": E_LIST_ID[5] + EXH_SEPARATOR + "N032",
    "Y_ЭКСГАУСТЕР А/М №5_КЛ1 ТР№5 ДО ЭД ЭКСГАУСТЕРА №5": E_LIST_ID[5] + EXH_SEPARATOR + "N033",
    "Y_ЭКСГАУСТЕР А/М №5_КЛ2 ТР№5 ДО ЭД ЭКСГАУСТЕРА №5": E_LIST_ID[5] + EXH_SEPARATOR + "N034",
    "Y_ЭКСГАУСТЕР А/М №5_КОЖУХ МУФТЫ ЭКСГ. №5": E_LIST_ID[5] + EXH_SEPARATOR + "N035",
    "Y_ЭКСГАУСТЕР А/М №5_КОРПУС ЭКСГ. №5": E_LIST_ID[5] + EXH_SEPARATOR + "N036",
    "Y_ЭКСГАУСТЕР А/М №5_МАСЛОНАСОС РАБОЧИЙ ЭКСГ. №5": E_LIST_ID[5] + EXH_SEPARATOR + "N037",
    "Y_ЭКСГАУСТЕР А/М №5_МАСЛОНАСОС ШЕСТЕРЕНЧАТЫЙ (РЕЗ.) ЭКСГ. №5": E_LIST_ID[5] + EXH_SEPARATOR + "N038",
    "Y_ЭКСГАУСТЕР А/М №5_МАСЛООХЛАДИТЕЛЬ  М-05-1 ЭКСГ. №5": E_LIST_ID[5] + EXH_SEPARATOR + "N039",
    "Y_ЭКСГАУСТЕР А/М №5_МАСЛОПРОВОДЫ ЭКСГАУСТЕРА №5": E_LIST_ID[5] + EXH_SEPARATOR + "N040",
    "Y_ЭКСГАУСТЕР А/М №5_МЕТРАН-100 ДАТЧИКИ ДАВЛЕНИЯ ЭКСГ.№5": E_LIST_ID[5] + EXH_SEPARATOR + "N041",
    "Y_ЭКСГАУСТЕР А/М №5_ПОДШИПНИК ОПОРНО-УПОРНЫЙ ЭКСГ. №5": E_LIST_ID[5] + EXH_SEPARATOR + "N042",
    "Y_ЭКСГАУСТЕР А/М №5_ПОДШИПНИК ОПОРНЫЙ №1": E_LIST_ID[5] + EXH_SEPARATOR + "N043",
    "Y_ЭКСГАУСТЕР А/М №5_ПОДШИПНИК ОПОРНЫЙ №2": E_LIST_ID[5] + EXH_SEPARATOR + "N044",
    "Y_ЭКСГАУСТЕР А/М №5_ПОДШИПНИК ОПОРНЫЙ ЭКСГ. №5": E_LIST_ID[5] + EXH_SEPARATOR + "N045",
    "Y_ЭКСГАУСТЕР А/М №5_РЕДУКТОР ГАЗ. ЗАДВИЖКИ ЭКСГ. №5": E_LIST_ID[5] + EXH_SEPARATOR + "N046",
    "Y_ЭКСГАУСТЕР А/М №5_РОТОР ЭКСГ. №5": E_LIST_ID[5] + EXH_SEPARATOR + "N047",
    "Y_ЭКСГАУСТЕР А/М №5_ТИРИСТ. ВОЗБУДИТЕЛЬ ВТ-РЭМ-400 ЭКСГ5 ВУ1": E_LIST_ID[5] + EXH_SEPARATOR + "N048",
    "Y_ЭКСГАУСТЕР А/М №5_ТИРИСТ. ВОЗБУДИТЕЛЬ ВТ-РЭМ-400 ЭКСГ5 ВУ2": E_LIST_ID[5] + EXH_SEPARATOR + "N049",
    "Y_ЭКСГАУСТЕР А/М №5_ТР-Р ТМ-4000-10/6 ЭКСГ. №5": E_LIST_ID[5] + EXH_SEPARATOR + "N050",
    "Y_ЭКСГАУСТЕР А/М №5_ТСМТ-101-010-50М-200 ТЕРМОПР.ПОДШ.Т.3": E_LIST_ID[5] + EXH_SEPARATOR + "N051",
    "Y_ЭКСГАУСТЕР А/М №5_ТСМТ-101-010-50М-400 ТЕРМОПР.ПОДШ.Т.2": E_LIST_ID[5] + EXH_SEPARATOR + "N052",
    "Y_ЭКСГАУСТЕР А/М №5_ТСМТ-101-010-50М-80 ТЕРМОПРЕОБР.МАСЛО": E_LIST_ID[5] + EXH_SEPARATOR + "N053",
    "Y_ЭКСГАУСТЕР А/М №5_ЭКСГАУСТЕР А/М №5": E_LIST_ID[5] + EXH_SEPARATOR + "N054",
    "Y_ЭКСГАУСТЕР А/М №5_ЭКСГАУСТЕР Н-8000 А/М №5": E_LIST_ID[5] + EXH_SEPARATOR + "N055",
    "Y_ЭКСГАУСТЕР А/М №5_ЭЛЕКТРОДВИГАТЕЛЬ ДСПУ-140-84-4 ЭКСГ. №5": E_LIST_ID[5] + EXH_SEPARATOR + "N056",
    "Y_ЭКСГАУСТЕР А/М №5_ЭЛЕКТРООБОРУДОВАНИЯ ЭКСГАУСТЕРА №5": E_LIST_ID[5] + EXH_SEPARATOR + "N057",
    "Y_ЭКСГАУСТЕР А/М №6_ВК 310С ВИБРОПРЕОБРАЗОВАТЕЛЬ ЭКСГ.№6 Т.2": E_LIST_ID[6] + EXH_SEPARATOR + "N058",
    "Y_ЭКСГАУСТЕР А/М №6_ВК 310С ВИБРОПРЕОБРАЗОВАТЕЛЬ ЭКСГ.№6 Т.3": E_LIST_ID[6] + EXH_SEPARATOR + "N059",
    "Y_ЭКСГАУСТЕР А/М №6_ГАЗОВАЯ ЗАДВИЖКА ЭКСГАУСТЕРА А/М №6": E_LIST_ID[6] + EXH_SEPARATOR + "N060",
    "Y_ЭКСГАУСТЕР А/М №6_ДВИГАТЕЛЬ ПУСКОВОГО МАСЛОНАСОСА ЭКСГ. №6": E_LIST_ID[6] + EXH_SEPARATOR + "N061",
    "Y_ЭКСГАУСТЕР А/М №6_ЗАДВИЖКА ЭКСГ. №6": E_LIST_ID[6] + EXH_SEPARATOR + "N062",
    "Y_ЭКСГАУСТЕР А/М №6_КЛ1 ТР№6 ДО ЭД ЭКСГАУСТЕРА №6": E_LIST_ID[6] + EXH_SEPARATOR + "N063",
    "Y_ЭКСГАУСТЕР А/М №6_КЛ2 ТР№6 ДО ЭД ЭКСГАУСТЕРА №6": E_LIST_ID[6] + EXH_SEPARATOR + "N064",
    "Y_ЭКСГАУСТЕР А/М №6_КОЖУХ МУФТЫ ЭКСГ. №6": E_LIST_ID[6] + EXH_SEPARATOR + "N065",
    "Y_ЭКСГАУСТЕР А/М №6_КОРПУС ЭКСГ. №6": E_LIST_ID[6] + EXH_SEPARATOR + "N066",
    "Y_ЭКСГАУСТЕР А/М №6_МАСЛОБАК ЭКСГ. №6": E_LIST_ID[6] + EXH_SEPARATOR + "N067",
    "Y_ЭКСГАУСТЕР А/М №6_МАСЛОНАСОС РАБОЧИЙ ЭКСГ. №6": E_LIST_ID[6] + EXH_SEPARATOR + "N068",
    "Y_ЭКСГАУСТЕР А/М №6_МАСЛОНАСОС ШЕСТЕРЕНЧАТЫЙ (ПУСК.) ЭКСГ.№6": E_LIST_ID[6] + EXH_SEPARATOR + "N069",
    "Y_ЭКСГАУСТЕР А/М №6_МАСЛООХЛАДИТЕЛЬ  М-05-1 ЭКСГ. №6": E_LIST_ID[6] + EXH_SEPARATOR + "N070",
    "Y_ЭКСГАУСТЕР А/М №6_МАСЛОПРОВОДЫ ЭКСГ №6": E_LIST_ID[6] + EXH_SEPARATOR + "N071",
    "Y_ЭКСГАУСТЕР А/М №6_ПОДШИПНИК ОПОРНО-УПОРНЫЙ ЭКСГ. №6": E_LIST_ID[6] + EXH_SEPARATOR + "N072",
    "Y_ЭКСГАУСТЕР А/М №6_ПОДШИПНИК ОПОРНЫЙ №1": E_LIST_ID[6] + EXH_SEPARATOR + "N073",
    "Y_ЭКСГАУСТЕР А/М №6_ПОДШИПНИК ОПОРНЫЙ №2": E_LIST_ID[6] + EXH_SEPARATOR + "N074",
    "Y_ЭКСГАУСТЕР А/М №6_ПОДШИПНИК ОПОРНЫЙ ЭКСГ. №6": E_LIST_ID[6] + EXH_SEPARATOR + "N075",
    "Y_ЭКСГАУСТЕР А/М №6_РЕДУКТОР ГАЗ. ЗАДВИЖКИ ЭКСГ. №6": E_LIST_ID[6] + EXH_SEPARATOR + "N076",
    "Y_ЭКСГАУСТЕР А/М №6_РОТОР ЭКСГ. №6": E_LIST_ID[6] + EXH_SEPARATOR + "N077",
    "Y_ЭКСГАУСТЕР А/М №6_САПФИР 22 МДД ПЕРЕПАД ДАВЛ. НА ЦИКЛОНЕ": E_LIST_ID[6] + EXH_SEPARATOR + "N078",
    "Y_ЭКСГАУСТЕР А/М №6_САПФИР 22 МДД РАЗРЕЖЕНИЕ В КОЛЛЕКТОРЕ": E_LIST_ID[6] + EXH_SEPARATOR + "N079",
    "Y_ЭКСГАУСТЕР А/М №6_ТИРИСТОРНЫЙ ВОЗБУДИТЕЛЬ ТВ-400 ЭКСГ6 ВУ1": E_LIST_ID[6] + EXH_SEPARATOR + "N080",
    "Y_ЭКСГАУСТЕР А/М №6_ТР-Р ТМ-4000-10/6 ЭКСГ. №6": E_LIST_ID[6] + EXH_SEPARATOR + "N081",
    "Y_ЭКСГАУСТЕР А/М №6_ЭКСГАУСТЕР А/М №6": E_LIST_ID[6] + EXH_SEPARATOR + "N082",
    "Y_ЭКСГАУСТЕР А/М №6_ЭЛЕКТРОДВИГАТЕЛЬ ДСПУ-140-84-4 ЭКСГ. №6": E_LIST_ID[6] + EXH_SEPARATOR + "N083",
    "Y_ЭКСГАУСТЕР А/М №6_ЭЛЕКТРООБОРУДОВАНИЯ ЭКСГ №6": E_LIST_ID[6] + EXH_SEPARATOR + "N084",
    "Y_ЭКСГАУСТЕР А/М №7_ВК 310С ВИБРОПРЕОБРАЗОВАТЕЛЬ ЭКСГ.№7 Т.2": E_LIST_ID[7] + EXH_SEPARATOR + "N085",
    "Y_ЭКСГАУСТЕР А/М №7_ВК 310С ВИБРОПРЕОБРАЗОВАТЕЛЬ ЭКСГ.№7 Т.3": E_LIST_ID[7] + EXH_SEPARATOR + "N086",
    "Y_ЭКСГАУСТЕР А/М №7_ВК 310С ВИБРОПРЕОБРАЗОВАТЕЛЬ ЭКСГ.№7 Т.4": E_LIST_ID[7] + EXH_SEPARATOR + "N087",
    "Y_ЭКСГАУСТЕР А/М №7_ГСМ ЭКСГ. №7": E_LIST_ID[7] + EXH_SEPARATOR + "N088",
    "Y_ЭКСГАУСТЕР А/М №7_ЗАДВИЖКА ЭКСГ. №7": E_LIST_ID[7] + EXH_SEPARATOR + "N089",
    "Y_ЭКСГАУСТЕР А/М №7_КЛ1 ТР№7 ДО ЭД ЭКСГАУСТЕРА №7": E_LIST_ID[7] + EXH_SEPARATOR + "N090",
    "Y_ЭКСГАУСТЕР А/М №7_КОЖУХ МУФТЫ ЭКСГ. №7": E_LIST_ID[7] + EXH_SEPARATOR + "N091",
    "Y_ЭКСГАУСТЕР А/М №7_КОРПУС ЭКСГ. №7": E_LIST_ID[7] + EXH_SEPARATOR + "N092",
    "Y_ЭКСГАУСТЕР А/М №7_МАСЛОНАСОС РАБОЧИЙ ЭКСГ. №7": E_LIST_ID[7] + EXH_SEPARATOR + "N093",
    "Y_ЭКСГАУСТЕР А/М №7_МАСЛОНАСОС ШЕСТЕРЕНЧАТЫЙ (ПУСК.) ЭКСГ.№7": E_LIST_ID[7] + EXH_SEPARATOR + "N094",
    "Y_ЭКСГАУСТЕР А/М №7_МАСЛООХЛАДИТЕЛЬ  М-05-1 ЭКСГ. №7": E_LIST_ID[7] + EXH_SEPARATOR + "N095",
    "Y_ЭКСГАУСТЕР А/М №7_МАСЛОПРОВОДЫ ЭКСГАУСТЕРА №7": E_LIST_ID[7] + EXH_SEPARATOR + "N096",
    "Y_ЭКСГАУСТЕР А/М №7_МАСЛЯНЫЙ ФИЛЬТР ЭКСГАУСТЕРА №7": E_LIST_ID[7] + EXH_SEPARATOR + "N097",
    "Y_ЭКСГАУСТЕР А/М №7_МЕТРАН-100 ДАТЧИКИ ДАВЛЕНИЯ ЭКСГ.№7": E_LIST_ID[7] + EXH_SEPARATOR + "N098",
    "Y_ЭКСГАУСТЕР А/М №7_ПОДШИПНИК ОПОРНО-УПОРНЫЙ ЭКСГ. №7": E_LIST_ID[7] + EXH_SEPARATOR + "N099",
    "Y_ЭКСГАУСТЕР А/М №7_ПОДШИПНИК ОПОРНЫЙ №1": E_LIST_ID[7] + EXH_SEPARATOR + "N100",
    "Y_ЭКСГАУСТЕР А/М №7_ПОДШИПНИК ОПОРНЫЙ №2": E_LIST_ID[7] + EXH_SEPARATOR + "N101",
    "Y_ЭКСГАУСТЕР А/М №7_ПОДШИПНИК ОПОРНЫЙ ЭКСГ. №7": E_LIST_ID[7] + EXH_SEPARATOR + "N102",
    "Y_ЭКСГАУСТЕР А/М №7_РЕГУЛИРУЮЩАЯ АППАРАТУРА ЭКСГАУСТЕРА №7": E_LIST_ID[7] + EXH_SEPARATOR + "N103",
    "Y_ЭКСГАУСТЕР А/М №7_РЕДУКТОР ГАЗ. ЗАДВИЖКИ ЭКСГ. №7": E_LIST_ID[7] + EXH_SEPARATOR + "N104",
    "Y_ЭКСГАУСТЕР А/М №7_РОТОР ЭКСГ. №7": E_LIST_ID[7] + EXH_SEPARATOR + "N105",
    "Y_ЭКСГАУСТЕР А/М №7_САПФИР 22 МДД ПЕРЕПАД ДАВЛ. НА ЦИКЛОНЕ": E_LIST_ID[7] + EXH_SEPARATOR + "N106",
    "Y_ЭКСГАУСТЕР А/М №7_ТИРИСТОРНЫЙ ВОЗБУДИТЕЛЬ ТВ-400 ЭКСГ7 ВУ1": E_LIST_ID[7] + EXH_SEPARATOR + "N107",
    "Y_ЭКСГАУСТЕР А/М №7_ТР-Р ТМ-4000-10/6 ЭКСГ. №7": E_LIST_ID[7] + EXH_SEPARATOR + "N108",
    "Y_ЭКСГАУСТЕР А/М №7_ТСМТ-101-010-50М-200 ТЕРМОПР.ПОДШ.Т.3": E_LIST_ID[7] + EXH_SEPARATOR + "N109",
    "Y_ЭКСГАУСТЕР А/М №7_ТСМТ-101-010-50М-400 ТЕРМОПР.ПОДШ.Т.1": E_LIST_ID[7] + EXH_SEPARATOR + "N110",
    "Y_ЭКСГАУСТЕР А/М №7_ТСМТ-101-010-50М-400 ТЕРМОПР.ПОДШ.Т.2": E_LIST_ID[7] + EXH_SEPARATOR + "N111",
    "Y_ЭКСГАУСТЕР А/М №7_ТСМТ-101-010-50М-80 ТЕРМОПРЕОБР.МАСЛО": E_LIST_ID[7] + EXH_SEPARATOR + "N112",
    "Y_ЭКСГАУСТЕР А/М №7_ЭКСГАУСТЕР А/М №7": E_LIST_ID[7] + EXH_SEPARATOR + "N113",
    "Y_ЭКСГАУСТЕР А/М №7_ЭЛ/ДВИГАТЕЛЬ ГАЗ. ЗАДВИЖКИ ЭКСГ. №7": E_LIST_ID[7] + EXH_SEPARATOR + "N114",
    "Y_ЭКСГАУСТЕР А/М №7_ЭЛЕКТРОДВИГАТЕЛЬ ДСПУ-140-84-4 ЭКСГ. №7": E_LIST_ID[7] + EXH_SEPARATOR + "N115",
    "Y_ЭКСГАУСТЕР А/М №7_ЭЛЕКТРООБОРУДОВАНИЯ ЭКСГАУСТЕРА №7": E_LIST_ID[7] + EXH_SEPARATOR + "N116",
    "Y_ЭКСГАУСТЕР А/М №8_ВК 310С ВИБРОПРЕОБРАЗОВАТЕЛЬ ЭКСГ.№8 Т.2": E_LIST_ID[8] + EXH_SEPARATOR + "N117",
    "Y_ЭКСГАУСТЕР А/М №8_ВК 310С ВИБРОПРЕОБРАЗОВАТЕЛЬ ЭКСГ.№8 Т.3": E_LIST_ID[8] + EXH_SEPARATOR + "N118",
    "Y_ЭКСГАУСТЕР А/М №8_ВК 310С ВИБРОПРЕОБРАЗОВАТЕЛЬ ЭКСГ.№8 Т.4": E_LIST_ID[8] + EXH_SEPARATOR + "N119",
    "Y_ЭКСГАУСТЕР А/М №8_ГСМ ЭКСГ. №8": E_LIST_ID[8] + EXH_SEPARATOR + "N120",
    "Y_ЭКСГАУСТЕР А/М №8_ЗАДВИЖКА ЭКСГ. №8": E_LIST_ID[8] + EXH_SEPARATOR + "N121",
    "Y_ЭКСГАУСТЕР А/М №8_ЗАПОРНАЯ АРМАТУРА ЭКСГАУСТЕРА №8": E_LIST_ID[8] + EXH_SEPARATOR + "N122",
    "Y_ЭКСГАУСТЕР А/М №8_КЛ1 ТР№8 ДО ЭД ЭКСГАУСТЕРА №8": E_LIST_ID[8] + EXH_SEPARATOR + "N123",
    "Y_ЭКСГАУСТЕР А/М №8_КЛ2 ТР№8 ДО ЭД ЭКСГАУСТЕРА №8": E_LIST_ID[8] + EXH_SEPARATOR + "N124",
    "Y_ЭКСГАУСТЕР А/М №8_КОЖУХ МУФТЫ ЭКСГ. №8": E_LIST_ID[8] + EXH_SEPARATOR + "N125",
    "Y_ЭКСГАУСТЕР А/М №8_КОРПУС ЭКСГ. №8": E_LIST_ID[8] + EXH_SEPARATOR + "N126",
    "Y_ЭКСГАУСТЕР А/М №8_МАСЛОНАСОС РАБОЧИЙ ЭКСГ. №8": E_LIST_ID[8] + EXH_SEPARATOR + "N127",
    "Y_ЭКСГАУСТЕР А/М №8_МАСЛОНАСОС ШЕСТЕРЕНЧАТЫЙ (ПУСК.) ЭКСГ.№8": E_LIST_ID[8] + EXH_SEPARATOR + "N128",
    "Y_ЭКСГАУСТЕР А/М №8_МАСЛОНАСОС ШЕСТЕРЕНЧАТЫЙ (РЕЗ.) ЭКСГ. №8": E_LIST_ID[8] + EXH_SEPARATOR + "N129",
    "Y_ЭКСГАУСТЕР А/М №8_МАСЛООХЛАДИТЕЛЬ  М-05-1 ЭКСГ. №8": E_LIST_ID[8] + EXH_SEPARATOR + "N130",
    "Y_ЭКСГАУСТЕР А/М №8_МАСЛОПРОВОДЫ ЭКСГАУСТЕРА №8": E_LIST_ID[8] + EXH_SEPARATOR + "N131",
    "Y_ЭКСГАУСТЕР А/М №8_МАСЛЯНЫЙ ФИЛЬТР ЭКСГАУСТЕРА №8": E_LIST_ID[8] + EXH_SEPARATOR + "N132",
    "Y_ЭКСГАУСТЕР А/М №8_ПОДШИПНИК ОПОРНО-УПОРНЫЙ ЭКСГ. №8": E_LIST_ID[8] + EXH_SEPARATOR + "N133",
    "Y_ЭКСГАУСТЕР А/М №8_ПОДШИПНИК ОПОРНЫЙ №1": E_LIST_ID[8] + EXH_SEPARATOR + "N134",
    "Y_ЭКСГАУСТЕР А/М №8_ПОДШИПНИК ОПОРНЫЙ №2": E_LIST_ID[8] + EXH_SEPARATOR + "N135",
    "Y_ЭКСГАУСТЕР А/М №8_ПОДШИПНИК ОПОРНЫЙ ЭКСГ. №8": E_LIST_ID[8] + EXH_SEPARATOR + "N136",
    "Y_ЭКСГАУСТЕР А/М №8_РЕДУКТОР ГАЗ. ЗАДВИЖКИ ЭКСГ. №8": E_LIST_ID[8] + EXH_SEPARATOR + "N137",
    "Y_ЭКСГАУСТЕР А/М №8_РОТОР ЭКСГ. №8": E_LIST_ID[8] + EXH_SEPARATOR + "N138",
    "Y_ЭКСГАУСТЕР А/М №8_ТИРИСТОРНЫЙ ВОЗБУДИТЕЛЬ СПВД-М10-400-5": E_LIST_ID[8] + EXH_SEPARATOR + "N139",
    "Y_ЭКСГАУСТЕР А/М №8_ТИРИСТОРНЫЙ ВОЗБУДИТЕЛЬ ТВ-400 ЭКСГ8 ВУ1": E_LIST_ID[8] + EXH_SEPARATOR + "N140",
    "Y_ЭКСГАУСТЕР А/М №8_ТР-Р ТМ-6300-10/6 ЭКСГ. №8": E_LIST_ID[8] + EXH_SEPARATOR + "N141",
    "Y_ЭКСГАУСТЕР А/М №8_ТСМТ-101-010-50М-200 ТЕРМОПР.ПОДШ.Т.4": E_LIST_ID[8] + EXH_SEPARATOR + "N142",
    "Y_ЭКСГАУСТЕР А/М №8_ТСМТ-101-010-50М-400 ТЕРМОПР.ПОДШ.Т.2": E_LIST_ID[8] + EXH_SEPARATOR + "N143",
    "Y_ЭКСГАУСТЕР А/М №8_ЭКСГАУСТЕР А/М №8": E_LIST_ID[8] + EXH_SEPARATOR + "N144",
    "Y_ЭКСГАУСТЕР А/М №8_ЭЛ/ДВИГАТЕЛЬ ГАЗ. ЗАДВИЖКИ ЭКСГ. №8": E_LIST_ID[8] + EXH_SEPARATOR + "N145",
    "Y_ЭКСГАУСТЕР А/М №8_ЭЛЕКТРОДВИГАТЕЛЬ ДСПУ-140-84-4 ЭКСГ. №8": E_LIST_ID[8] + EXH_SEPARATOR + "N146",
    "Y_ЭКСГАУСТЕР А/М №8_ЭЛЕКТРООБОРУДОВАНИЯ ЭКСГАУСТЕРА №8": E_LIST_ID[8] + EXH_SEPARATOR + "N147",
    "Y_ЭКСГАУСТЕР А/М №9_ВК 310С ВИБРОПРЕОБРАЗОВАТЕЛЬ ЭКСГ.№9 Т.1": E_LIST_ID[9] + EXH_SEPARATOR + "N148",
    "Y_ЭКСГАУСТЕР А/М №9_ГСМ ЭКСГ. №9": E_LIST_ID[9] + EXH_SEPARATOR + "N149",
    "Y_ЭКСГАУСТЕР А/М №9_ДВИГАТЕЛЬ ПУСКОВОГО МАСЛОНАСОСА ЭКСГ. №9": E_LIST_ID[9] + EXH_SEPARATOR + "N150",
    "Y_ЭКСГАУСТЕР А/М №9_ЗАДВИЖКА ЭКСГ. №9": E_LIST_ID[9] + EXH_SEPARATOR + "N151",
    "Y_ЭКСГАУСТЕР А/М №9_ЗАПОРНАЯ АРМАТУРА ЭКСГАУСТЕРА №9": E_LIST_ID[9] + EXH_SEPARATOR + "N152",
    "Y_ЭКСГАУСТЕР А/М №9_КЛ1 ТР№9 ДО ЭД ЭКСГАУСТЕРА №9": E_LIST_ID[9] + EXH_SEPARATOR + "N153",
    "Y_ЭКСГАУСТЕР А/М №9_КОЖУХ МУФТЫ ЭКСГ. №9": E_LIST_ID[9] + EXH_SEPARATOR + "N154",
    "Y_ЭКСГАУСТЕР А/М №9_КОРПУС ЭКСГ. №9": E_LIST_ID[9] + EXH_SEPARATOR + "N155",
    "Y_ЭКСГАУСТЕР А/М №9_МАСЛОНАСОС РАБОЧИЙ ЭКСГ. №9": E_LIST_ID[9] + EXH_SEPARATOR + "N156",
    "Y_ЭКСГАУСТЕР А/М №9_МАСЛООХЛАДИТЕЛЬ  М-05-1 ЭКСГ. №9": E_LIST_ID[9] + EXH_SEPARATOR + "N157",
    "Y_ЭКСГАУСТЕР А/М №9_МАСЛОПРОВОДЫ ЭКСГАУСТЕРА №9": E_LIST_ID[9] + EXH_SEPARATOR + "N158",
    "Y_ЭКСГАУСТЕР А/М №9_МАСЛОСТАНЦИЯ ЖИДКОЙ СМАЗКИ ЭКСГ. №9": E_LIST_ID[9] + EXH_SEPARATOR + "N159",
    "Y_ЭКСГАУСТЕР А/М №9_МЕТРАН-100 ДАТЧИКИ ДАВЛЕНИЯ ЭКСГ.№9": E_LIST_ID[9] + EXH_SEPARATOR + "N160",
    "Y_ЭКСГАУСТЕР А/М №9_ПОДШИПНИК ОПОРНО-УПОРНЫЙ ЭКСГ. №9": E_LIST_ID[9] + EXH_SEPARATOR + "N161",
    "Y_ЭКСГАУСТЕР А/М №9_ПОДШИПНИК ОПОРНЫЙ №1": E_LIST_ID[9] + EXH_SEPARATOR + "N162",
    "Y_ЭКСГАУСТЕР А/М №9_ПОДШИПНИК ОПОРНЫЙ №2": E_LIST_ID[9] + EXH_SEPARATOR + "N163",
    "Y_ЭКСГАУСТЕР А/М №9_ПОДШИПНИК ОПОРНЫЙ ЭКСГ. №9": E_LIST_ID[9] + EXH_SEPARATOR + "N164",
    "Y_ЭКСГАУСТЕР А/М №9_РЕДУКТОР ГАЗ. ЗАДВИЖКИ ЭКСГ. №9": E_LIST_ID[9] + EXH_SEPARATOR + "N165",
    "Y_ЭКСГАУСТЕР А/М №9_РОТОР ЭКСГ. №9": E_LIST_ID[9] + EXH_SEPARATOR + "N166",
    "Y_ЭКСГАУСТЕР А/М №9_ТИРИСТОРНЫЙ ВОЗБУДИТЕЛЬ ТВ-400 ЭКСГ9 ВУ1": E_LIST_ID[9] + EXH_SEPARATOR + "N167",
    "Y_ЭКСГАУСТЕР А/М №9_ТР-Р ТМ-6300-10/6 ЭКСГ. №9": E_LIST_ID[9] + EXH_SEPARATOR + "N168",
    "Y_ЭКСГАУСТЕР А/М №9_ТСМТ-101-010-50М-400 ТЕРМОПР.ПОДШ.Т.1": E_LIST_ID[9] + EXH_SEPARATOR + "N169",
    "Y_ЭКСГАУСТЕР А/М №9_ТСМТ-101-010-50М-80 ТЕРМОПРЕОБР.МАСЛО": E_LIST_ID[9] + EXH_SEPARATOR + "N170",
    "Y_ЭКСГАУСТЕР А/М №9_ЭКСГАУСТЕР А/М №9": E_LIST_ID[9] + EXH_SEPARATOR + "N171",
    "Y_ЭКСГАУСТЕР А/М №9_ЭЛ/ДВИГАТЕЛЬ ГАЗ. ЗАДВИЖКИ ЭКСГ. №9": E_LIST_ID[9] + EXH_SEPARATOR + "N172",
    "Y_ЭКСГАУСТЕР А/М №9_ЭЛЕКТРОАППАРАТУРА ЭКСГ. №9": E_LIST_ID[9] + EXH_SEPARATOR + "N173",
    "Y_ЭКСГАУСТЕР А/М №9_ЭЛЕКТРОДВИГАТЕЛЬ ДСПУ-140-84-4 ЭКСГ. №9": E_LIST_ID[9] + EXH_SEPARATOR + "N174",
    "Y_ЭКСГАУСТЕР А/М №9_ЭЛЕКТРООБОРУДОВАНИЯ ЭКСГАУСТЕРА №9": E_LIST_ID[9] + EXH_SEPARATOR + "N175",
}

EXH_ID_BY_TP_ID = {pm_name: pm_name.split(EXH_SEPARATOR)[0] for pm_name in Y_LIST.values()}

MODULES_PARAM_GROUPS = {
    "initdb": ["db", "constants", "utils"],
    "start": ["db", "constants", "utils", "prediction"],
    "update": ["db", "constants", "utils"],
    "predict": ["db", "constants", "utils", "prediction"]
}
